# Generated by Django 4.2.30 on 2026-04-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('contact', 'Contato'), ('group', 'Grupo')], max_length=10)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
