# Generated by Django 4.2.30 on 2026-04-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_jid', models.CharField(max_length=100)),
                ('target_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('text', 'Só texto'), ('file', 'Só arquivo'), ('file_text', 'Arquivo + texto')], max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recur_days', models.CharField(blank=True, default='', help_text="'all' para todos os dias, 'weekdays' para Seg-Sex", max_length=20)),
                ('batch_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Enviando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
